name: Deploy firebase functions
on:
    push:
      branches:
      - production
jobs:
    main:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@master

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'
    
        - name: Install Dependencies
          run: cd back/functions && npm install
    
        - name: Generate TSOA Specs and Routes
          run: cd back/functions && npm run deploy
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TINA_MARTINS }}